"""
Steam-Oil Ratio (SOR) and Economic Valuation Calculator for CSS Operations.

Pure, deterministic functions for thermal efficiency, energy costs,
and net economic value including mechanical risk penalties and marginal stopping.
"""

from __future__ import annotations

# Standard oilfield conversion: 1 tonne Cold Water Equivalent (CWE) = 6.2898 bbl
CWE_TONNES_TO_BBL = 6.2898

# Industry benchmark cost defaults for heavy-oil thermal recovery (WCS)
DEFAULT_OIL_PRICE_PER_BBL = 65.00  # USD / bbl
DEFAULT_STEAM_COST_PER_TONNE = 32.00  # USD / tonne steam
DEFAULT_WATER_DISPOSAL_PER_BBL = 2.50  # USD / bbl produced water
DEFAULT_DAILY_LIFT_ELECTRIC_COST = 85.00  # USD / day SRP pumping power
DEFAULT_WORKOVER_EVENT_COST = 18000.00  # USD average pulling / rod workover


def steam_oil_ratio(cumulative_steam_cwe: float, cumulative_oil: float) -> float:
    """
    Compute volumetric Steam-Oil Ratio (m3 steam CWE / m3 oil or bbl/bbl).

    Args:
        cumulative_steam_cwe: Total steam injected in metric tonnes (CWE).
        cumulative_oil: Total oil produced in barrels (bbl).

    Returns:
        Volumetric Steam-Oil Ratio. Returns inf if cumulative_oil <= 0.
    """
    if cumulative_oil <= 0.0:
        return float("inf")
    steam_bbl = cumulative_steam_cwe * CWE_TONNES_TO_BBL
    return round(steam_bbl / cumulative_oil, 2)


def energy_cost_per_barrel(
    steam_cost: float, energy_cost: float, oil_produced: float
) -> float:
    """
    Compute total thermal and electrical energy cost per barrel of oil produced.

    Args:
        steam_cost: Total cost of steam generation (USD).
        energy_cost: Total electrical lift / pumping cost (USD).
        oil_produced: Total oil produced (bbl).

    Returns:
        Energy cost in USD/bbl. Returns inf if oil_produced <= 0.
    """
    if oil_produced <= 0.0:
        return float("inf")
    total_energy = steam_cost + energy_cost
    return round(total_energy / oil_produced, 2)


def economic_value(
    oil_price: float,
    oil_produced: float,
    steam_cost: float,
    energy_cost: float,
    water_handling_cost: float,
    mechanical_risk_cost: float = 0.0,
) -> float:
    """
    Compute net economic value generated by a CSS cycle.

    Net Value = Revenue - (Steam Generation + Power Lift + Water Handling + Risk Penalty)

    Args:
        oil_price: Realized price per barrel (USD/bbl).
        oil_produced: Total clean oil produced (bbl).
        steam_cost: Cost of generating injected steam (USD).
        energy_cost: Electricity cost for artificial lift (USD).
        water_handling_cost: Water disposal and treating costs (USD).
        mechanical_risk_cost: Expected risk cost of mechanical failure/parting (USD).

    Returns:
        Net economic value in USD.
    """
    revenue = oil_price * oil_produced
    total_opex = steam_cost + energy_cost + water_handling_cost + mechanical_risk_cost
    return round(revenue - total_opex, 2)


def marginal_daily_value(
    daily_oil_bbl: float,
    daily_water_bbl: float,
    oil_price: float = DEFAULT_OIL_PRICE_PER_BBL,
    daily_lift_cost: float = DEFAULT_DAILY_LIFT_ELECTRIC_COST,
    water_cost_per_bbl: float = DEFAULT_WATER_DISPOSAL_PER_BBL,
    daily_risk_penalty: float = 0.0,
) -> float:
    """
    Compute marginal net cash flow for operating one additional day.

    Marginal Stopping Rule: If Marginal Value <= 0, continuing production
    costs more in lift and water disposal than oil revenue brings in.

    Returns:
        Marginal net dollar value for the day.
    """
    marginal_revenue = daily_oil_bbl * oil_price
    marginal_costs = (
        daily_lift_cost + (daily_water_bbl * water_cost_per_bbl) + daily_risk_penalty
    )
    return round(marginal_revenue - marginal_costs, 2)
